name: Run Library API Tests

# When should this action run?
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest # The server OS

        steps:
            # Step 1: Download your code from the repo
            - uses: actions/checkout@v3

            # Step 2: Install Python
            - name: Set up Python 3.14
              uses: actions/setup-python@v4
              with:
                  python-version: "3.14"

            # Step 3: Install Flask, Pytest, etc.
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            # Step 4: Run the tests!
            - name: Test with pytest
              run: |
                  pytest
